version: 2.1

jobs:
  setup:
    executor:
      name: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r 'Sprint/Sprint Implementation/Exam_Office_System/myproject/requirements.txt'

  test:
    executor:
      name: python/default
    steps:
      - checkout
      - run:
          name: Run pytest for all apps
          command: |
            cd 'Sprint/Sprint Implementation/Exam_Office_System/myproject'
            for app in $(ls -d */); do
              pytest $app/tests
            done

  docs:
    executor:
      name: python/default
    steps:
      - checkout
      - run:
          name: Build Sphinx documentation
          command: |
            cd 'Sprint/Sprint Implementation/Exam_Office_System/myproject/source'
            make html

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - main
                - ci-test-branch
      - test:
          requires:
            - setup
          filters:
            branches:
              only:
                - main
                - ci-test-branch
      - docs:
          requires:
            - setup
          filters:
            branches:
              only:
                - main
                - ci-test-branch
