version: 2.1

jobs:
  setup:
    machine:  # Use the machine executor
    steps:
      - checkout
      - run:
          name: Install Python and dependencies
          command: |
            sudo apt update
            sudo apt install -y python3-pip python3-venv
            python3 -m venv env
            source env/bin/activate
            pip install --upgrade pip
            pip install -r 'Sprint/Sprint Implementation/Exam_Office_System/myproject/requirements.txt'
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    machine:
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run pytest for all apps
          command: |
            cd 'Sprint/Sprint Implementation/Exam_Office_System/myproject'
            for app in $(ls -d */); do
              pytest $app/tests || exit 1  # Fail if any test fails

  docs:
    machine:
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Sphinx documentation
          command: |
            cd 'Sprint/Sprint Implementation/Exam_Office_System/myproject/source'
            make html
      - persist_to_workspace:
          root: .
          paths:
            - 'Sprint/Sprint Implementation/Exam_Office_System/myproject/source/_build'

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - main
                - ci-test-branch
      - test:
          requires:
            - setup
          filters:
            branches:
              only:
                - main
                - ci-test-branch
      - docs:
          requires:
            - setup
          filters:
            branches:
              only:
                - main
                - ci-test-branch
